### ISSUE TITLE
Random recipes are broken

### ISSUE THREAD

**Issue by ACGaming** [Trico-Everfire/TETAN-WR#1]
When using this mod, random recipes no longer work, although JEI displays them normally. [This has been noticed in my modpack Hardcore Nightmare IV](https://cdn.discordapp.com/attachments/519895890308104194/780529313321058335/unknown.png), but can already be reproduced with just the crafting station from Tinkers' Construct:

![](https://i.imgur.com/M7GV8Im.png)

The usual crafting table or inventory crafting from Vanilla Minecraft are apparently randomly affected as well.

The mods I used to reproduce the issue:
- ToughAsNails-1.12.2-3.1.0.141-universal **or** SimpleDifficulty-1.12.2-0.3.4
- TATANWR-1.2.0-1.12.2
- Mantle-1.12-1.3.3.55
- TConstruct-1.12.2-2.13.0.183

**Comment by Trico-Everfire** [comment]
it may be a problem with the way filters are repaired, i'll look into it soon.

**Comment by Taknax** [comment]
The bug is getting weirder if installed alongside with NoMoreRecipeConflict. Then its even not possible to craft a wooden shovel.

**Comment by ENDERZOMBI102** [comment]
this only happens in the crafting station

**Comment by ACGaming** [comment]
> this only happens in the crafting station

This affected the 2x2 inventory crafting grid for me as well.

**Comment by Trico-Everfire** [comment]
> > this only happens in the crafting station
> 
> This affected the 2x2 inventory crafting grid for me as well.

I have been working on the fix (sorry for the late reply, IRL life came first)
but I cannot test it currently, could I send you a snapshot for you to test? as currently I cannot test.

**Comment by Trico-Everfire** [comment]
According to those who have tested it, it has been fixed, thank you all for your patience.
